### ISSUE TITLE
Request - URL hyperlink as a file?

### ISSUE THREAD

**Issue by gloschtla** [ScreamingHawk/phone-saver#38] opened 2017-07-16 12:12 UTC
Support request. Generated by Phone Saver.

Intent type: text/plain
Intent action: android.intent.action.SEND
Text: http://archive.is
Subject: Webpage archive
URL Content-Type: text/html

**Comment by ScreamingHawk** [comment] 2017-07-18 23:35
Duplicate of #30 

Thanks for posting the ticket! It's good to see the level of interest

**Closed by ScreamingHawk** 2017-07-18 23:35 UTC
Labels: duplicate
